name: Build

on:
  workflow_call:
    inputs:
      gcr-registry:
        required: true
        type: string
        description: "GCR registry URL (e.g., gcr.io/project-id)"
      gcr-repository:
        required: true
        type: string
        description: "Repository name in GCR"
      context:
        required: false
        type: string
        description: "Build context directory"
        default: "."
      version:
        required: true
        type: string
        description: "Version to tag the Docker image"
      PROJECT_ID:
        required: true
        type: string
        description: "GCP Project ID"
    secrets:
      GCP_SA_KEY:
        required: true
        description: "GCP Service Account JSON key"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${inputs.PROJECT_ID}

      - name: Build Application
        run: go build -v ./...

      - name: Authenticate with GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ inputs.gcr-registry }}/${{ inputs.gcr-repository }}:${{ inputs.version }} ${{ inputs.context }}
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://${{ inputs.gcr-registry }}
          docker push ${{ inputs.gcr-registry }}/${{ inputs.gcr-repository }}:${{ inputs.version }}