name: Production Deployment

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          # Replace with actual production deployment commands
          kubectl apply -f k8s/prod.yaml