name: Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rollback Deployment
        run: |
          # Replace with actual rollback commands
          kubectl rollout undo deployment/my-app